### ISSUE TITLE
After yarn install and yarn start there is an error

### ISSUE THREAD

**Issue by Mandy9943** [multiversx/mx-utils-dapp#115]
All is white screen and in the console there is an error.

![image](https://github.com/multiversx/mx-utils-dapp/assets/74042888/19cfbaed-0c12-440f-9cf2-4414ddabf10e)

**Comment by radumojic** [comment]
Hello!

There might be a compatibility issue with node/the build system here.

If you relace the line here: https://github.com/multiversx/mx-utils-dapp/blob/main/vite.config.ts#L32
with: `process: { ...process, env: process.env }`

are you able to start the project ?
